#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' /etc/hosts
